### ISSUE TITLE
"info" paradas

### ISSUE THREAD

**Issue by juanrarodriguez18** [ManuelLR/Sevilla-Bus#12]
Cuando resaltamos una parada, sólo se muestra el número de las líneas pertenecientes a éstas, sería más intuitivo mostrar además un mensaje o cabecera del tipo "bús:" o "líneas:".

**Comment by ManuelLR** [comment]
## Opción 1

![opcion1_visualizacion 2](https://cloud.githubusercontent.com/assets/12049827/16176393/4cf34238-360e-11e6-8814-a08fe1306388.png)
![opcion1_visualizacion 1](https://cloud.githubusercontent.com/assets/12049827/16176394/4cf6e30c-360e-11e6-8728-74039b2a9bc7.png)

**PROBLEMA**: Parece estar limitado a 4 líneas 

## Opción 2

![opcion2_visualizacion 2](https://cloud.githubusercontent.com/assets/12049827/16176399/5f348402-360e-11e6-9ce0-45c42127a800.png)
![opcion2_visualizacion 1](https://cloud.githubusercontent.com/assets/12049827/16176400/5f35634a-360e-11e6-8554-dad1216634f0.png)

**PROBLEMA**: Parece ser más confuso ya que la información en esa vista (y en toda la aplicación) se muestra de manera horizontal y eso sería vertical causando posibles confusiones.

## Opción 3

**(Modificación de la 1)**

![opcion3_visualizacion 2](https://cloud.githubusercontent.com/assets/12049827/16176432/988db9ac-360f-11e6-8d0e-ce8a6064346b.png)
![opcion3_visualizacion 1](https://cloud.githubusercontent.com/assets/12049827/16176431/988daf2a-360f-11e6-9dbc-8137b0484a18.png)

**VENTAJAS**:
- Caben 6 líneas
- No interfiere con el diseño de la aplicación
